version: '3.8'

services:
  rsvp:
    image: python:3.11-slim
    container_name: rsvp-app
    working_dir: /app
    volumes:
      - app_data:/app/data
    restart: unless-stopped

volumes:
  app_data:
    ports:
      - "8080:3022"
    environment:
      - ADMIN_PASSWORD=letmein  # Change this for security
    command: >
      sh -c "
      pip install --no-cache-dir -r requirements.txt &&
      python app.py
      "
    restart: unless-stopped

volumes:
  app_data:
